apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jync

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# 换镜像仓库/版本只改这里:
# images:
#   - name: jync
#     newName: registry.example.com/qqmu/jync
#     newTag: "1.3.2"
